FROM python:3.7

WORKDIR /app

COPY . .

CMD python bmi.py

#docker build python-app -t lucaster/assignment1_pythonapp:1
#docker run -i -t --name assignment1_pythonapp_1 --rm lucaster/assignment1_pythonapp
